application: catsorgsite
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css

- url: /imgs
  static_dir: static/imgs

- url: /admin.*
  script: admin.py
  login: admin

- url: .*
  script: main.py
