application: catsorgsite
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /admin.*
  script: admin/admin.py
  login: admin

- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.png

- url: /svc/.*
  script: svc.py

- url: .*
  script: main.py
